<?php

namespace App\Http\Controllers;

use Illuminate\Http\JsonResponse;

class HeroController extends Controller
{
    public function index(): JsonResponse
    {
        return response()->json($this->heroes());
    }

    private function heroes(): array
    {
        return [
            [
                'id' => 'crusader',
                'name' => 'Crusader',
                'title' => 'The Holy Warrior',
                'color' => '#c8a951',
                'optimalRanks' => [1, 2],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 35, 'speed' => 2, 'dodge' => 0, 'accuracy' => 10, 'damageMin' => 10, 'damageMax' => 16, 'crit' => 3, 'prot' => 0],
                'resistances' => ['stun' => 40, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 40, 'debuff' => 30, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Smite', 'ranks' => [1,2,3], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Strong melee attack with Holy damage bonus vs Undead'],
                    ['name' => 'Holy Lance', 'ranks' => [1,2,3,4], 'targets' => [3,4], 'type' => 'attack', 'description' => 'Reaches back rows, bonus damage to Unholy'],
                    ['name' => 'Stunning Blow', 'ranks' => [1,2], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Chance to stun, slight forward move'],
                    ['name' => 'Bulwark of Faith', 'ranks' => [1,2,3], 'targets' => [0], 'type' => 'support', 'description' => 'Self PROT+, guard ally, party stress heal'],
                    ['name' => 'Battle Heal', 'ranks' => [1,2,3], 'targets' => [1,2,3,4], 'type' => 'heal', 'description' => 'Heals ally HP, cures bleed and blight'],
                    ['name' => 'Inspiring Cry', 'ranks' => [1,2,3], 'targets' => [0], 'type' => 'support', 'description' => 'Party stress heal, SPD+, ACC+'],
                ],
                'description' => 'A stalwart melee fighter blessed with divine power. Excels in ranks 1 and 2, laying low the Undead with righteous fury. His Battle Heal makes him a capable support in a pinch.',
                'rankWarnings' => [
                    '4' => 'Crusader in rank 4 cannot use Smite or Stunning Blow. Only Holy Lance remains — severely limits his offense.',
                    '3' => 'Crusader in rank 3 has limited melee options. Best used for support (Inspiring Cry, Battle Heal) from this position.',
                ],
                'synergyNotes' => ['Holy damage bonus demolishes Ruins Undead enemies.', 'Pairs well with Vestal for reliable sustained healing.'],
            ],
            [
                'id' => 'plague_doctor',
                'name' => 'Plague Doctor',
                'title' => 'The Physician of Pestilence',
                'color' => '#7a4a9e',
                'optimalRanks' => [3, 4],
                'targetRanks' => [1, 2, 3, 4],
                'stats' => ['hp' => 20, 'speed' => 6, 'dodge' => 20, 'accuracy' => 5, 'damageMin' => 4, 'damageMax' => 7, 'crit' => 4, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 50, 'bleed' => 30, 'disease' => 50, 'move' => 50, 'debuff' => 40, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Noxious Blast', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Medium blight, slight stun chance'],
                    ['name' => 'Disorienting Blast', 'ranks' => [2,3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Stuns target, applies ACC debuff'],
                    ['name' => 'Blinding Gas', 'ranks' => [3,4], 'targets' => [2,3], 'type' => 'debuff', 'description' => 'Multi-target ACC debuff (blind) — game-changing vs. high ACC enemies'],
                    ['name' => 'Incision', 'ranks' => [1,2,3], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Bleed attack with moderate damage'],
                    ['name' => 'Battlefield Medicine', 'ranks' => [2,3,4], 'targets' => [1,2,3,4], 'type' => 'heal', 'description' => 'Heals HP and cures blight, bleed, and disease'],
                    ['name' => 'Emboldening Vapours', 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'support', 'description' => 'Target ally gains CRIT+ and SPD+'],
                ],
                'description' => 'A versatile back-line specialist who debuffs, stuns, blights, and cures. Her high speed and dodge make her surprisingly durable despite low HP. Essential in the Warrens and Cove.',
                'rankWarnings' => [
                    '1' => 'Plague Doctor in rank 1 cannot use Noxious Blast, Blinding Gas, or Emboldening Vapours. Severely hampered — she needs the back ranks.',
                    '2' => 'Plague Doctor in rank 2 loses Noxious Blast and Blinding Gas. Sub-optimal but Battlefield Medicine still works.',
                ],
                'synergyNotes' => ['Blinding Gas provides massive ACC debuffs critical vs. elites.', 'Emboldening Vapours on a Highwayman or Grave Robber enables devastating crit chains.'],
            ],
            [
                'id' => 'leper',
                'name' => 'Leper',
                'title' => 'The Broken Lord',
                'color' => '#8a6a4a',
                'optimalRanks' => [1],
                'targetRanks' => [1, 2],
                'stats' => ['hp' => 40, 'speed' => 1, 'dodge' => -10, 'accuracy' => -5, 'damageMin' => 12, 'damageMax' => 18, 'crit' => 3, 'prot' => 10],
                'resistances' => ['stun' => 60, 'blight' => 50, 'bleed' => 50, 'disease' => 50, 'move' => 80, 'debuff' => 50, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Chop', 'ranks' => [1,2], 'targets' => [1,2], 'type' => 'attack', 'description' => 'High damage melee, hits ranks 1-2'],
                    ['name' => 'Hew', 'ranks' => [1,2], 'targets' => [1,2], 'type' => 'attack', 'description' => 'High damage, slight bleed chance'],
                    ['name' => 'Revenge', 'ranks' => [1], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Massive bonus damage below 50% HP'],
                    ['name' => 'Solemnity', 'ranks' => [1,2], 'targets' => [0], 'type' => 'support', 'description' => 'Cure self blight and bleed, stress heal'],
                    ['name' => 'Withstand', 'ranks' => [1,2], 'targets' => [0], 'type' => 'support', 'description' => 'Self PROT+, HP regen, guard self'],
                ],
                'description' => 'A devastating frontline warrior with the highest raw damage potential in the game. His low ACC requires accuracy-boosting trinkets. Nearly immune to movement and stun effects.',
                'rankWarnings' => [
                    '3' => 'Leper in rank 3 cannot use any attack skills whatsoever. Completely non-functional offensively.',
                    '4' => 'Leper in rank 4 cannot attack or use any meaningful skills. An emergency — remove him immediately.',
                ],
                'synergyNotes' => ['Pair with Jester (Dirge) to offset his low speed.', 'Occultist Vulnerability Hex + Leper = catastrophic damage output.'],
            ],
            [
                'id' => 'highwayman',
                'name' => 'Highwayman',
                'title' => 'The Brigand of Fortune',
                'color' => '#4a5568',
                'optimalRanks' => [2, 3],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 22, 'speed' => 5, 'dodge' => 15, 'accuracy' => 10, 'damageMin' => 6, 'damageMax' => 12, 'crit' => 8, 'prot' => 0],
                'resistances' => ['stun' => 20, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 30, 'debuff' => 40, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Pistol Shot', 'ranks' => [2,3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Reliable ranged attack with good crit chance'],
                    ['name' => 'Wicked Slice', 'ranks' => [1,2], 'targets' => [1,2], 'type' => 'attack', 'description' => 'High crit melee with bleed'],
                    ['name' => "Duelist's Advance", 'ranks' => [2,3], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Move forward, heavy bleed application'],
                    ['name' => 'Open Vein', 'ranks' => [1,2], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Extremely heavy bleed stack'],
                    ['name' => 'Point Blank Shot', 'ranks' => [1,2], 'targets' => [1], 'type' => 'attack', 'description' => 'Devastating single-target hit, self-pushes back'],
                    ['name' => 'Grapeshot Blast', 'ranks' => [2,3], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Multi-target shot with blight chance'],
                ],
                'description' => 'A flexible and reliable fighter operating from ranks 1-3. Point Blank Shot is one of the hardest-hitting single attacks in the game. Good dodge for survivability.',
                'rankWarnings' => [
                    '4' => 'Highwayman in rank 4 can only use Pistol Shot. He loses his versatility and bleed utility drastically.',
                    '1' => 'Highwayman in rank 1 loses Pistol Shot. Can still use Wicked Slice and Open Vein — acceptable but not ideal.',
                ],
                'synergyNotes' => ['Bleed combos with Hellion or Grave Robber stack rapidly.', 'High base crit pairs excellently with Plague Doctor Emboldening Vapours.'],
            ],
            [
                'id' => 'grave_robber',
                'name' => 'Grave Robber',
                'title' => 'The Morbid Treasure Hunter',
                'color' => '#2d6b64',
                'optimalRanks' => [2, 3, 4],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 19, 'speed' => 7, 'dodge' => 25, 'accuracy' => 10, 'damageMin' => 5, 'damageMax' => 9, 'crit' => 12, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 50, 'bleed' => 30, 'disease' => 50, 'move' => 30, 'debuff' => 40, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Lunge', 'ranks' => [2,3,4], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Highest crit multiplier in the game — moves self forward'],
                    ['name' => 'Pick to the Face', 'ranks' => [1,2,3], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Blight application with decent range'],
                    ['name' => 'Thrown Dagger', 'ranks' => [2,3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Ranged dagger with high crit and bleed'],
                    ['name' => 'Flashing Daggers', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Multi-target bleed on all enemies'],
                    ['name' => 'Shadow Fade', 'ranks' => [1,2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Retreat, gain massive DODGE+, stress heal'],
                ],
                'description' => 'The fastest, most evasive hero. Exceptional crit rates make her a glass cannon. Lunge has the highest crit modifier in the game. Shadow Fade provides crucial repositioning.',
                'rankWarnings' => [
                    '1' => 'Grave Robber in rank 1 cannot use Lunge, Thrown Dagger, or Flashing Daggers. Her kit is crippled — avoid.',
                ],
                'synergyNotes' => ['Lunge + crit trinkets can one-shot back rank enemies.', 'Jester Solo + Grave Robber Lunge = potentially 80+ damage in one hit.'],
            ],
            [
                'id' => 'jester',
                'name' => 'Jester',
                'title' => 'The Mad Minstrel',
                'color' => '#8b3a8b',
                'optimalRanks' => [2, 3],
                'targetRanks' => [1, 2, 3, 4],
                'stats' => ['hp' => 21, 'speed' => 8, 'dodge' => 20, 'accuracy' => 10, 'damageMin' => 5, 'damageMax' => 9, 'crit' => 10, 'prot' => 0],
                'resistances' => ['stun' => 20, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 20, 'debuff' => 40, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Dirge', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Party SPD+, stress heal all — critical for slow heroes'],
                    ['name' => 'Solo', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'support', 'description' => "Next ally attack deals +50% DMG — one of the game's best buffs"],
                    ['name' => 'Battle Ballad', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Party ACC+ and CRIT+, excellent pre-boss buff'],
                    ['name' => 'Slice Off', 'ranks' => [1,2,3], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Moderate bleed, self push-forward'],
                    ['name' => 'Harvest', 'ranks' => [2,3], 'targets' => [1,2,3,4], 'type' => 'attack', 'description' => 'Long range bleed, self stress heal'],
                    ['name' => 'Inspiring Tune', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Large stress heal for entire party — best stress tool'],
                ],
                'description' => 'The premier party support hero. His buffs (Solo, Battle Ballad, Dirge) can transform any hero into a monster. Inspiring Tune is the best stress management skill in the game.',
                'rankWarnings' => [
                    '1' => 'Jester in rank 1 cannot use any support skills. He completely loses his identity as a buffer and stress healer.',
                    '4' => 'Jester in rank 4 loses Slice Off. Support skills still work, but he feels cornered and less flexible.',
                ],
                'synergyNotes' => ['Solo + Grave Robber Lunge can exceed 100 damage.', 'Dirge is critical for Leper who has the lowest speed in the game.'],
            ],
            [
                'id' => 'arbalest',
                'name' => 'Arbalest',
                'title' => 'The Sharpshooter',
                'color' => '#2d5a27',
                'optimalRanks' => [3, 4],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 27, 'speed' => 4, 'dodge' => 5, 'accuracy' => 10, 'damageMin' => 9, 'damageMax' => 17, 'crit' => 5, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 40, 'debuff' => 30, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Rallying Flare', 'ranks' => [3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Remove Blind/Stun from ally, shuffle one enemy'],
                    ['name' => 'Sharpen Spear', 'ranks' => [3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Self ACC+ and CRIT+ — stacks indefinitely each turn'],
                    ['name' => 'Sniper Shot', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Highest single-target ranged damage, can hit any rank'],
                    ['name' => 'Knock Back', 'ranks' => [3,4], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Pushes enemy back two ranks, disrupting formations'],
                    ['name' => 'Battlefield Bandage', 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'heal', 'description' => 'Heals HP and cures bleed — secondary healer'],
                ],
                'description' => 'A powerful ranged attacker built for the back ranks. Sharpen Spear stacking followed by Sniper Shot creates devastating burst windows. Battlefield Bandage adds surprise utility.',
                'rankWarnings' => [
                    '1' => 'Arbalest in rank 1 cannot use any skills at all. Completely non-functional.',
                    '2' => 'Arbalest in rank 2 cannot use any skills at all. She must remain in ranks 3 or 4.',
                ],
                'synergyNotes' => ['Stack Sharpen Spear twice before boss fights for huge crit damage.', 'Knock Back disrupts enemy formation and denies powerful front-rank skills.'],
            ],
            [
                'id' => 'bounty_hunter',
                'name' => 'Bounty Hunter',
                'title' => 'The Grim Manhunter',
                'color' => '#8b4500',
                'optimalRanks' => [2, 3],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 25, 'speed' => 4, 'dodge' => 5, 'accuracy' => 10, 'damageMin' => 7, 'damageMax' => 13, 'crit' => 7, 'prot' => 0],
                'resistances' => ['stun' => 40, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 30, 'debuff' => 30, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Collect Bounty', 'ranks' => [1,2,3], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Massive bonus damage vs. Stunned enemies'],
                    ['name' => 'Come Hither', 'ranks' => [2,3], 'targets' => [2,3,4], 'type' => 'attack', 'description' => 'Pulls enemy to rank 1, huge bonus vs. Humans'],
                    ['name' => 'Uppercut', 'ranks' => [1,2,3], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Stuns target, pushes them back one rank'],
                    ['name' => 'Finish Him', 'ranks' => [1,2,3], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'High damage bonus vs. Marked targets'],
                    ['name' => 'Mark for Death', 'ranks' => [1,2,3,4], 'targets' => [1,2,3,4], 'type' => 'debuff', 'description' => 'Marks enemy — entire party gains ACC+ vs. marked target'],
                ],
                'description' => 'A control specialist who thrives on Stunned and Marked targets. Mark for Death boosts your entire party. Come Hither pulls dangerous back-row enemies into melee range.',
                'rankWarnings' => [
                    '4' => 'Bounty Hunter in rank 4 loses Come Hither, Collect Bounty, Uppercut, and Finish Him. Nearly useless — only Mark for Death works.',
                    '1' => 'Bounty Hunter in rank 1 loses Come Hither. His stun/mark combo still works but he loses the critical pull utility.',
                ],
                'synergyNotes' => ['Mark for Death + any high-damage hero obliterates elites.', 'Uppercut → Collect Bounty is an incredibly damaging two-round combo.'],
            ],
            [
                'id' => 'hellion',
                'name' => 'Hellion',
                'title' => 'The Savage Fighter',
                'color' => '#8a0303',
                'optimalRanks' => [1, 2],
                'targetRanks' => [1, 2, 3, 4],
                'stats' => ['hp' => 27, 'speed' => 3, 'dodge' => 5, 'accuracy' => 5, 'damageMin' => 8, 'damageMax' => 14, 'crit' => 5, 'prot' => 0],
                'resistances' => ['stun' => 20, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 20, 'debuff' => 20, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'If It Bleeds', 'ranks' => [1,2], 'targets' => [1,2,3,4], 'type' => 'attack', 'description' => 'Heavy bleed applied to any rank — unique reach'],
                    ['name' => 'Barbaric Yawp', 'ranks' => [1,2], 'targets' => [0], 'type' => 'support', 'description' => 'Party stress heal, stuns adjacent enemies'],
                    ['name' => 'Iron Swan', 'ranks' => [1,2], 'targets' => [3,4], 'type' => 'attack', 'description' => 'Hits back row enemies, self push-back'],
                    ['name' => 'Breakthrough', 'ranks' => [1,2], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Hits 3 targets in a line, moves self forward'],
                    ['name' => 'Bleed Out', 'ranks' => [1,2], 'targets' => [1,2,3,4], 'type' => 'attack', 'description' => 'Heaviest bleed in game, self PROT-'],
                ],
                'description' => 'An aggressive frontline brawler with unparalleled bleed application. If It Bleeds targets any rank. Barbaric Yawp provides rare front-row stress healing and free stuns.',
                'rankWarnings' => [
                    '3' => 'Hellion in rank 3 cannot use If It Bleeds, Barbaric Yawp, Breakthrough, or Bleed Out. She is severely limited.',
                    '4' => 'Hellion in rank 4 cannot use any attack skills. Iron Swan still works but she is mostly non-functional.',
                ],
                'synergyNotes' => ['Bleed stacking with Grave Robber or Highwayman is devastating.', 'Breakthrough hits 3 enemies — ideal against swarming Warrens encounters.'],
            ],
            [
                'id' => 'man_at_arms',
                'name' => 'Man-at-Arms',
                'title' => 'The Veteran Soldier',
                'color' => '#2b4a7e',
                'optimalRanks' => [1, 2, 3],
                'targetRanks' => [1, 2, 3, 4],
                'stats' => ['hp' => 30, 'speed' => 2, 'dodge' => 5, 'accuracy' => 5, 'damageMin' => 8, 'damageMax' => 14, 'crit' => 3, 'prot' => 15],
                'resistances' => ['stun' => 40, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 50, 'debuff' => 50, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Crush', 'ranks' => [1,2], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Moderate damage with stun chance'],
                    ['name' => 'Rampart', 'ranks' => [1,2,3], 'targets' => [1,2,3,4], 'type' => 'support', 'description' => 'Guard + riposte — protects low HP ally with counter-attacks'],
                    ['name' => 'Bolster', 'ranks' => [1,2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Party SPD+, DODGE+, self stress heal'],
                    ['name' => "Defender's Stance", 'ranks' => [1,2,3], 'targets' => [0], 'type' => 'support', 'description' => 'Self PROT+, guard adjacent ally, riposte counter'],
                    ['name' => 'Retribution', 'ranks' => [1,2,3], 'targets' => [0], 'type' => 'support', 'description' => 'Self guard + powerful riposte counter'],
                    ['name' => 'Command', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Party ACC+ and CRIT+ — one of the strongest party buffs in the game'],
                ],
                'description' => 'The ultimate defensive support hero. Rampart guard mechanics protect fragile allies. Command is one of the best party-wide buffs. Functional from nearly any rank.',
                'rankWarnings' => [
                    '4' => 'Man-at-Arms in rank 4 loses Crush, Rampart, and Defender\'s Stance. Still uses Command and Bolster but loses his defensive identity.',
                ],
                'synergyNotes' => ["Command + any high-damage hero produces terrifying output.", 'Rampart guarding a Flagellant near Death\'s Door enables Redeem healing.'],
            ],
            [
                'id' => 'occultist',
                'name' => 'Occultist',
                'title' => 'The Dark Wanderer',
                'color' => '#4a1a7e',
                'optimalRanks' => [3, 4],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 20, 'speed' => 5, 'dodge' => 10, 'accuracy' => 5, 'damageMin' => 5, 'damageMax' => 9, 'crit' => 6, 'prot' => 0],
                'resistances' => ['stun' => 20, 'blight' => 40, 'bleed' => 40, 'disease' => 40, 'move' => 20, 'debuff' => 60, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Wyrd Reconstruction', 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'heal', 'description' => 'Random HP heal — can be massive or cause bleed. High risk, high reward.'],
                    ['name' => 'Vulnerability Hex', 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'debuff', 'description' => 'Enemy PROT- — enables your party to deal significantly more damage'],
                    ['name' => 'Weakening Curse', 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'debuff', 'description' => 'Enemy DMG- — reduces incoming damage from dangerous foes'],
                    ['name' => 'Abyssal Artillery', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Eldritch ranged damage'],
                    ['name' => "Daemon's Pull", 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'attack', 'description' => 'Bleeds enemy and pulls them forward'],
                ],
                'description' => 'A high-risk, high-reward healer and debuffer. Wyrd Reconstruction can save a hero from Death\'s Door — or accidentally apply bleed. Vulnerability Hex amplifies your entire party\'s damage.',
                'rankWarnings' => [
                    '1' => 'Occultist in rank 1 cannot use any skills. Completely non-functional.',
                    '2' => 'Occultist in rank 2 cannot use any skills. He must remain in ranks 3 or 4 at all times.',
                ],
                'synergyNotes' => ['Vulnerability Hex + Leper = catastrophic physical damage.', 'High debuff resistance (60%) makes him surprisingly resilient to enemy debuffs.'],
            ],
            [
                'id' => 'vestal',
                'name' => 'Vestal',
                'title' => 'The Devoted Sister',
                'color' => '#1a4a8a',
                'optimalRanks' => [3, 4],
                'targetRanks' => [1, 2, 3, 4],
                'stats' => ['hp' => 24, 'speed' => 4, 'dodge' => 5, 'accuracy' => 5, 'damageMin' => 5, 'damageMax' => 9, 'crit' => 4, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 30, 'bleed' => 30, 'disease' => 50, 'move' => 30, 'debuff' => 40, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Divine Grace', 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'heal', 'description' => 'Reliable single-target HP heal — core skill'],
                    ['name' => 'Divine Comfort', 'ranks' => [3,4], 'targets' => [0], 'type' => 'heal', 'description' => 'AoE party heal — lower value but heals everyone'],
                    ['name' => 'Judgment', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Holy attack with bonus damage to Unholy enemies'],
                    ['name' => 'Dazzling Light', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Stuns enemy with moderate damage'],
                    ['name' => 'Illumination', 'ranks' => [3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Raises torch level mid-dungeon, party stress heal'],
                    ['name' => 'Mace Bash', 'ranks' => [1,2], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Basic melee for when she is pushed forward'],
                ],
                'description' => 'The most reliable healer in the game. Divine Grace and Divine Comfort provide unmatched sustain. Illumination can save a run by raising torch level. Cannot party with Abomination.',
                'rankWarnings' => [
                    '1' => 'Vestal in rank 1 cannot heal at all. A displaced Vestal only has Mace Bash — a near-total loss of her function.',
                    '2' => 'Vestal in rank 2 loses all healing skills. Use Illumination to raise torch level only.',
                ],
                'incompatibleWith' => ['abomination'],
                'synergyNotes' => ['Essential healer in the Ruins where Undead resist blight-based healing.', 'Illumination is a lifesaver when the torch runs low deep in the dungeon.'],
            ],
            [
                'id' => 'houndmaster',
                'name' => 'Houndmaster',
                'title' => 'The Dog and His Man',
                'color' => '#6b7c2a',
                'optimalRanks' => [2, 3, 4],
                'targetRanks' => [1, 2, 3, 4],
                'stats' => ['hp' => 23, 'speed' => 5, 'dodge' => 15, 'accuracy' => 10, 'damageMin' => 5, 'damageMax' => 9, 'crit' => 10, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 40, 'debuff' => 40, 'deathBlow' => 67],
                'skills' => [
                    ['name' => "Hound's Rush", 'ranks' => [2,3,4], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Dog attacks with bleed and stun chance'],
                    ['name' => 'Cry Havoc', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Party stress heal + DODGE+ — rare front-accessible stress heal'],
                    ['name' => "Hound's Harry", 'ranks' => [1,2,3], 'targets' => [1,2,3,4], 'type' => 'attack', 'description' => "Dog bites any rank target, applies bleed"],
                    ['name' => 'Target Whistle', 'ranks' => [2,3,4], 'targets' => [1,2,3,4], 'type' => 'debuff', 'description' => 'Mark enemy — dog attacks marked target for huge bonus damage'],
                    ['name' => 'Whistle', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Party DODGE+, self stress heal'],
                    ['name' => 'Lick Wounds', 'ranks' => [1,2,3,4], 'targets' => [0], 'type' => 'heal', 'description' => 'Self HP regen, cures bleed and blight, stress heal'],
                ],
                'description' => 'An incredibly flexible support-attacker. Cry Havoc provides valuable stress healing. High trap resistance is excellent for scouting. Hound\'s Harry can target any rank position.',
                'rankWarnings' => [
                    '1' => "Houndmaster in rank 1 loses Hound's Rush, Cry Havoc, and Target Whistle. Significantly hampered — place him in ranks 2-4.",
                ],
                'synergyNotes' => ["Target Whistle + Hound's Rush = reliable stun-and-bleed combo.", 'Highest trap resistance in game — ideal scout for hallways.'],
            ],
            [
                'id' => 'abomination',
                'name' => 'Abomination',
                'title' => 'The Tortured Soul',
                'color' => '#6a2a0a',
                'optimalRanks' => [2, 3],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 25, 'speed' => 4, 'dodge' => 5, 'accuracy' => 5, 'damageMin' => 7, 'damageMax' => 12, 'crit' => 5, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 40, 'bleed' => 50, 'disease' => 40, 'move' => 30, 'debuff' => 40, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Rake', 'ranks' => [1,2,3], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Moderate damage with bleed chance'],
                    ['name' => 'Toss', 'ranks' => [1,2], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Pushes enemy back two ranks, disrupting formation'],
                    ['name' => 'Transform', 'ranks' => [1,2,3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Gain stress, unlock devastating beast form abilities'],
                    ['name' => 'Slam (Beast)', 'ranks' => [1,2], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Massive AoE damage hitting 3 enemies in beast form'],
                    ['name' => 'Immobilize (Beast)', 'ranks' => [1,2], 'targets' => [1,2,3,4], 'type' => 'attack', 'description' => 'Stuns ALL enemies simultaneously in beast form'],
                    ['name' => 'Absolution', 'ranks' => [1,2,3,4], 'targets' => [0], 'type' => 'heal', 'description' => 'Cure self blight and disease, large stress heal — returns to human'],
                ],
                'description' => 'A unique hero who transforms into a powerful beast at the cost of stress. Immobilize in beast form can stun the entire enemy party. Cannot party with Vestal or Crusader (religious conflict).',
                'rankWarnings' => [
                    '4' => 'Abomination in rank 4 cannot attack as human or beast. He is entirely non-functional offensively.',
                ],
                'incompatibleWith' => ['vestal', 'crusader'],
                'synergyNotes' => ['Beast form Immobilize + Bounty Hunter Collect Bounty = incredible burst.', 'Plague Doctor can cure the stress caused by transformation.'],
            ],
            [
                'id' => 'flagellant',
                'name' => 'Flagellant',
                'title' => 'The Penitent',
                'color' => '#5a0a1a',
                'optimalRanks' => [2, 3, 4],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 22, 'speed' => 5, 'dodge' => 0, 'accuracy' => 10, 'damageMin' => 6, 'damageMax' => 10, 'crit' => 4, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 30, 'bleed' => 70, 'disease' => 50, 'move' => 30, 'debuff' => 50, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Punish', 'ranks' => [2,3,4], 'targets' => [1,2], 'type' => 'attack', 'description' => 'Bonus damage when self at Death\'s Door — his premier attack'],
                    ['name' => 'Reclaim', 'ranks' => [2,3,4], 'targets' => [1,2,3,4], 'type' => 'heal', 'description' => 'Heals ally at cost of own HP and self-bleed'],
                    ['name' => 'Redeem', 'ranks' => [2,3,4], 'targets' => [0], 'type' => 'heal', 'description' => 'Massive self-heal when near Death\'s Door + party stress heal'],
                    ['name' => 'Suffer', 'ranks' => [2,3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Applies blight and bleed combo, self-bleed'],
                    ['name' => 'Exsanguinate', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Highest bleed application in the entire game'],
                    ['name' => 'Profuse Bleeding', 'ranks' => [2,3,4], 'targets' => [1,2,3,4], 'type' => 'attack', 'description' => 'AoE bleed applied to all enemies simultaneously'],
                ],
                'description' => 'A masochistic warrior who grows more powerful the closer he is to death. Highest bleed resistance in game. Reclaim sacrifices his HP to heal allies. Extremely high-skill ceiling.',
                'rankWarnings' => [
                    '1' => 'Flagellant in rank 1 cannot use Punish, Reclaim, Exsanguinate, or Profuse Bleeding. He must stay in ranks 2-4.',
                ],
                'synergyNotes' => ['Exsanguinate is the most powerful bleed skill in the game.', 'Man-at-Arms Rampart on Flagellant at Death\'s Door enables his Redeem mega-heal.'],
            ],
            [
                'id' => 'musketeer',
                'name' => 'Musketeer',
                'title' => 'The Veteran Sharpshooter',
                'color' => '#1a2a5a',
                'optimalRanks' => [3, 4],
                'targetRanks' => [1, 2, 3],
                'stats' => ['hp' => 27, 'speed' => 4, 'dodge' => 5, 'accuracy' => 10, 'damageMin' => 9, 'damageMax' => 17, 'crit' => 5, 'prot' => 0],
                'resistances' => ['stun' => 30, 'blight' => 30, 'bleed' => 30, 'disease' => 30, 'move' => 40, 'debuff' => 30, 'deathBlow' => 67],
                'skills' => [
                    ['name' => 'Musket Shot', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Powerful ranged attack, hits any front row rank'],
                    ['name' => 'True Aim', 'ranks' => [3,4], 'targets' => [0], 'type' => 'support', 'description' => 'Self ACC+ and CRIT+ stacking — same as Sharpen Spear'],
                    ['name' => 'Suppressing Fire', 'ranks' => [3,4], 'targets' => [1,2,3], 'type' => 'attack', 'description' => 'Pushes enemy back, applies SPD debuff'],
                    ['name' => 'Camping Bandage', 'ranks' => [3,4], 'targets' => [1,2,3,4], 'type' => 'heal', 'description' => 'Heals HP and cures bleed (DLC camp skill)'],
                ],
                'description' => 'A DLC variant of the Arbalest with identical stats and similar role. Use the Musketeer for her distinct trinket synergies or aesthetic preference.',
                'rankWarnings' => [
                    '1' => 'Musketeer in rank 1 cannot use any skills. Completely non-functional.',
                    '2' => 'Musketeer in rank 2 cannot use any skills. Must stay in ranks 3 or 4.',
                ],
                'synergyNotes' => ['Same tactical synergies as Arbalest.', 'True Aim stacking before boss fights can enable near-guaranteed crits.'],
            ],
        ];
    }
}
